In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("C:/Users/PRITAM/Downloads/customer_data.csv")

In [3]:
data.describe()

       Transaction_ID          Age      Referal  Amount_spent
count     2512.000000  2470.000000  2357.000000   2270.000000
mean    152443.931131    46.637652     0.652100   1418.422577
std        724.580482    18.186277     0.476405    878.507451
min     151200.000000    15.000000     0.000000      2.090000
25%     151815.750000    32.000000     0.000000    678.192500
50%     152443.500000    47.000000     1.000000   1341.435000
75%     153071.250000    62.000000     1.000000   2038.102500
max     153699.000000    78.000000     1.000000   2999.980000

In [5]:
data["Age"].mean()
data["Age"].median()
data["Age"].mode()
data["Age"].std()

np.float64(18.186276792698017)

In [6]:
data["Age"].median()

np.float64(47.0)

In [7]:
data["Age"].mode()

0    54.0
Name: Age, dtype: float64

In [8]:
data["Age"].std()

np.float64(18.186276792698017)

In [9]:
data["Age"].min()

np.float64(15.0)

In [10]:
data["Age"].max()

np.float64(78.0)

In [13]:
data["State_names"].unique()

array(['Kansas', 'Illinois', 'New Mexico', 'Virginia', 'Connecticut',
       'Hawaii', 'Florida', 'Vermont', 'California', 'Colorado', 'Iowa',
       'South Carolina', 'New York', 'Maine', 'Maryland', 'Missouri',
       'North Dakota', 'Ohio', 'Nebraska', 'Montana', 'Indiana',
       'Wisconsin', 'Alabama', 'Arkansas', 'Pennsylvania',
       'New Hampshire', 'Washington', 'Texas', 'Kentucky',
       'Massachusetts', 'Wyoming', 'Louisiana', 'North Carolina',
       'Rhode Island', 'West Virginia', 'Tennessee', 'Oregon', 'Alaska',
       'Oklahoma', 'Nevada', 'New Jersey', 'Michigan', 'Utah', 'Arizona',
       'South Dakota', 'Georgia', 'Idaho', 'Mississippi', 'Minnesota',
       'Delaware'], dtype=object)

In [14]:
data["State_names"].value_counts()

State_names
Illinois          67
Georgia           64
Massachusetts     63
Maine             62
Kentucky          59
Minnesota         59
Missouri          57
Delaware          56
Arizona           56
New York          55
Nevada            55
Arkansas          55
New Mexico        55
California        55
Vermont           54
West Virginia     54
New Jersey        53
Florida           53
Oregon            53
Colorado          52
Connecticut       52
Pennsylvania      52
Washington        52
South Dakota      52
Michigan          52
Iowa              51
Rhode Island      51
Texas             49
Louisiana         49
Montana           48
Virginia          46
Hawaii            46
North Carolina    46
South Carolina    45
Idaho             45
Wisconsin         45
Maryland          45
Wyoming           44
Mississippi       44
Oklahoma          44
Ohio              43
Utah              43
New Hampshire     43
Indiana           43
Alabama           42
Kansas            41
North Dakota      41
Nebraska          41
Alaska            41
Tennessee         39
Name: count, dtype: int64

In [16]:
data["State_names"].nunique() #Total number of unique() items

50

In [17]:
data["Gender"].nunique()

2

In [18]:
data["Gender"].value_counts()

Gender
Female    1356
Male      1128
Name: count, dtype: int64

In [21]:
data["State_names"].sort_values()

617     Alabama
1856    Alabama
2443    Alabama
2441    Alabama
1023    Alabama
         ...
1789    Wyoming
1811    Wyoming
1819    Wyoming
1844    Wyoming
119     Wyoming
Name: State_names, Length: 2512, dtype: object

In [20]:
data.sort_values(by="State_names")

,Transaction_date,Transaction_ID,Gender,Age,Marital_status,State_names,Segment,Employees_status,Payment_method,Referal,Amount_spent
617,09-09-2020,151805,Male,43.0,Married,Alabama,Silver,Employees,PayPal,1.0,87.88
1856,31-01-2024,153044,Female,18.0,Married,Alabama,Silver,workers,PayPal,NaN,2091.73
2443,09-09-2025,153631,Male,60.0,Married,Alabama,Platinum,Employees,PayPal,1.0,NaN
2441,07-09-2025,153629,Male,18.0,Single,Alabama,Platinum,Employees,Card,0.0,289.85
1023,20-10-2021,152211,Female,30.0,Married,Alabama,Platinum,Unemployment,Other,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1789,25-11-2023,152977,Female,36.0,Married,Wyoming,Silver,Employees,PayPal,1.0,698.92
1811,17-12-2023,152999,Male,71.0,Married,Wyoming,Basic,Unemployment,PayPal,0.0,1647.30
1819,25-12-2023,153007,Male,35.0,Married,Wyoming,Basic,workers,Card,0.0,984.70
1844,19-01-2024,153032,Female,24.0,Married,Wyoming,Basic,Unemployment,PayPal,1.0,16.27
119,30-04-2019,151307,Female,43.0,Married,Wyoming,Basic,Employees,Card,1.0,914.94

In [22]:
data.sort_values(by="State_names").head()

,Transaction_date,Transaction_ID,Gender,Age,Marital_status,State_names,Segment,Employees_status,Payment_method,Referal,Amount_spent
617,09-09-2020,151805,Male,43.0,Married,Alabama,Silver,Employees,PayPal,1.0,87.88
1856,31-01-2024,153044,Female,18.0,Married,Alabama,Silver,workers,PayPal,NaN,2091.73
2443,09-09-2025,153631,Male,60.0,Married,Alabama,Platinum,Employees,PayPal,1.0,NaN
2441,07-09-2025,153629,Male,18.0,Single,Alabama,Platinum,Employees,Card,0.0,289.85
1023,20-10-2021,152211,Female,30.0,Married,Alabama,Platinum,Unemployment,Other,0.0,NaN

In [23]:
data["Amount_spent"].nlargest()

17      2999.98
485     2998.62
2279    2997.21
589     2997.15
743     2996.82
Name: Amount_spent, dtype: float64

In [24]:
data["Amount_spent"].nsmallest()

2468    2.09
568     2.16
2401    2.84
962     5.31
860     5.55
Name: Amount_spent, dtype: float64

In [27]:
data.display("Payment_method" == PayPal)

AttributeError: 'DataFrame' object has no attribute 'display'

In [28]:
data.display()

AttributeError: 'DataFrame' object has no attribute 'display'

In [30]:
data["Payment_method" == PayPal]

NameError: name 'PayPal' is not defined

In [32]:
data[data['Payment_method']=='PayPal']

,Transaction_date,Transaction_ID,Gender,Age,Marital_status,State_names,Segment,Employees_status,Payment_method,Referal,Amount_spent
2,03-01-2019,151202,Male,63.0,Married,New Mexico,Basic,workers,PayPal,1.0,1572.60
5,06-01-2019,151205,Male,71.0,Single,Hawaii,Basic,Employees,PayPal,1.0,2922.66
6,07-01-2019,151206,Female,34.0,Married,New Mexico,Platinum,Employees,PayPal,1.0,1481.42
7,08-01-2019,151207,Male,37.0,Married,Connecticut,Basic,workers,PayPal,1.0,1149.55
10,11-01-2019,151210,Female,56.0,Married,California,Basic,Employees,PayPal,0.0,1712.82
...,...,...,...,...,...,...,...,...,...,...,...
2503,08-11-2025,153691,Male,67.0,Single,Colorado,Basic,Employees,PayPal,0.0,511.50
2508,13-11-2025,153696,Female,36.0,Married,Hawaii,Silver,self-employed,PayPal,1.0,708.88
2509,14-11-2025,153697,Male,22.0,Single,South Carolina,Basic,workers,PayPal,1.0,2030.07
2510,15-11-2025,153698,NaN,44.0,Single,New York,Basic,Employees,PayPal,0.0,1909.77
2511,16-11-2025,153699,Male,48.0,Single,California,Silver,workers,PayPal,1.0,1073.15

In [33]:
condition=data['Payment_method']=='PayPal'
data[condition]

,Transaction_date,Transaction_ID,Gender,Age,Marital_status,State_names,Segment,Employees_status,Payment_method,Referal,Amount_spent
2,03-01-2019,151202,Male,63.0,Married,New Mexico,Basic,workers,PayPal,1.0,1572.60
5,06-01-2019,151205,Male,71.0,Single,Hawaii,Basic,Employees,PayPal,1.0,2922.66
6,07-01-2019,151206,Female,34.0,Married,New Mexico,Platinum,Employees,PayPal,1.0,1481.42
7,08-01-2019,151207,Male,37.0,Married,Connecticut,Basic,workers,PayPal,1.0,1149.55
10,11-01-2019,151210,Female,56.0,Married,California,Basic,Employees,PayPal,0.0,1712.82
...,...,...,...,...,...,...,...,...,...,...,...
2503,08-11-2025,153691,Male,67.0,Single,Colorado,Basic,Employees,PayPal,0.0,511.50
2508,13-11-2025,153696,Female,36.0,Married,Hawaii,Silver,self-employed,PayPal,1.0,708.88
2509,14-11-2025,153697,Male,22.0,Single,South Carolina,Basic,workers,PayPal,1.0,2030.07
2510,15-11-2025,153698,NaN,44.0,Single,New York,Basic,Employees,PayPal,0.0,1909.77
2511,16-11-2025,153699,Male,48.0,Single,California,Silver,workers,PayPal,1.0,1073.15

In [37]:
condition1=data['Payment_method']=='PayPal' 
condition2=data['Marital_status']=='Married' 
data[(condition1) & (condition2)]

,Transaction_date,Transaction_ID,Gender,Age,Marital_status,State_names,Segment,Employees_status,Payment_method,Referal,Amount_spent
2,03-01-2019,151202,Male,63.0,Married,New Mexico,Basic,workers,PayPal,1.0,1572.60
6,07-01-2019,151206,Female,34.0,Married,New Mexico,Platinum,Employees,PayPal,1.0,1481.42
7,08-01-2019,151207,Male,37.0,Married,Connecticut,Basic,workers,PayPal,1.0,1149.55
10,11-01-2019,151210,Female,56.0,Married,California,Basic,Employees,PayPal,0.0,1712.82
16,17-01-2019,151216,Female,72.0,Married,Maine,Silver,self-employed,PayPal,1.0,2882.77
...,...,...,...,...,...,...,...,...,...,...,...
2489,25-10-2025,153677,Female,77.0,Married,Idaho,Basic,workers,PayPal,NaN,1524.83
2490,26-10-2025,153678,Female,50.0,Married,Illinois,Silver,self-employed,PayPal,1.0,1453.75
2492,28-10-2025,153680,Female,33.0,Married,Oregon,Basic,Employees,PayPal,1.0,716.58
2494,30-10-2025,153682,Male,56.0,Married,Wisconsin,Basic,workers,PayPal,1.0,1888.91
2508,13-11-2025,153696,Female,36.0,Married,Hawaii,Silver,self-employed,PayPal,1.0,708.88

In [38]:
data[['Age', 'Amount_spent']].groupby(data['Gender']).max()

         Age  Amount_spent
Gender
Female  78.0       2999.98
Male    78.0       2998.62