In [1]:
import numpy as np

In [2]:
import pandas as pd

In [5]:
data = pd.read_excel("C:/Users/PRITAM/Downloads/Anudip Foundation/Excel & Power BI/Facilitator Led Session Questions/Bank Details.xlsx")

In [6]:
data

      Customer ID       Name   Surname  Gender  Age            Region
0       100000001      Simon     Walsh    Male   21           England
1       400000002    Jasmine    Miller  Female   34  Northern Ireland
2       100000003       Liam     Brown    Male   46           England
3       300000004     Trevor      Parr    Male   32             Wales
4       100000005    Deirdre   Pullman  Female   38           England
...           ...        ...       ...     ...  ...               ...
4009    200004010        Sam     Lewis    Male   64          Scotland
4010    200004011      Keith    Hughes    Male   52          Scotland
4011    200004012     Hannah  Springer  Female   50          Scotland
4012    200004013  Christian      Reid    Male   51          Scotland
4013    300004014    Stephen       May    Male   33             Wales

[4014 rows x 6 columns]

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4014 entries, 0 to 4013
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer ID  4014 non-null   int64
 1   Name         4014 non-null   object
 2   Surname      4014 non-null   object
 3   Gender       4014 non-null   object
 4   Age          4014 non-null   int64
 5   Region       4014 non-null   object
dtypes: int64(2), object(4)
memory usage: 188.3+ KB

In [10]:
data.head() #top 5 records by default

   Customer ID     Name  Surname  Gender  Age            Region
0    100000001    Simon    Walsh    Male   21           England
1    400000002  Jasmine   Miller  Female   34  Northern Ireland
2    100000003     Liam    Brown    Male   46           England
3    300000004   Trevor     Parr    Male   32             Wales
4    100000005  Deirdre  Pullman  Female   38           England

In [9]:
data.tail() #below 5 data

      Customer ID       Name   Surname  Gender  Age    Region
4009    200004010        Sam     Lewis    Male   64  Scotland
4010    200004011      Keith    Hughes    Male   52  Scotland
4011    200004012     Hannah  Springer  Female   50  Scotland
4012    200004013  Christian      Reid    Male   51  Scotland
4013    300004014    Stephen       May    Male   33     Wales

In [11]:
data.head(10) #In this case top 10 records will come

   Customer ID     Name   Surname  Gender  Age            Region
0    100000001    Simon     Walsh    Male   21           England
1    400000002  Jasmine    Miller  Female   34  Northern Ireland
2    100000003     Liam     Brown    Male   46           England
3    300000004   Trevor      Parr    Male   32             Wales
4    100000005  Deirdre   Pullman  Female   38           England
5    300000006      Ava   Coleman  Female   30             Wales
6    100000007  Dorothy   Thomson  Female   34           England
7    200000008     Lisa      Knox  Female   48          Scotland
8    300000009     Ruth  Campbell  Female   33             Wales
9    100000010  Dominic      Parr    Male   42           England

In [12]:
data.describe()

        Customer ID          Age
count  4.014000e+03  4014.000000
mean   1.696831e+08    38.611111
std    8.865374e+07     9.819121
min    1.000000e+08    15.000000
25%    1.000020e+08    31.000000
50%    1.000038e+08    37.000000
75%    2.000031e+08    45.000000
max    4.000038e+08    64.000000

In [13]:
data.count()

Customer ID    4014
Name           4014
Surname        4014
Gender         4014
Age            4014
Region         4014
dtype: int64

In [14]:
data.max()

Customer ID    400003848
Name                 Zoe
Surname            Young
Gender              Male
Age                   64
Region             Wales
dtype: object

In [15]:
data["Age"].max()

np.int64(64)

In [16]:
data["Age"].mean()

np.float64(38.611111111111114)

In [17]:
data["Age"].value_counts()

Age
34    185
36    183
33    167
37    166
31    163
35    163
32    161
38    159
29    139
42    133
40    132
39    126
30    125
41    125
43    121
45    117
44    105
28    104
27     96
47     93
46     91
48     84
52     77
26     76
51     75
25     67
49     67
53     66
50     65
24     58
54     49
55     47
23     46
58     45
56     42
57     34
59     34
61     31
22     31
18     30
60     29
21     27
20     20
19     19
64     15
63     11
62     10
17      4
15      1
Name: count, dtype: int64

In [18]:
data["Age"].duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4009     True
4010     True
4011     True
4012     True
4013     True
Name: Age, Length: 4014, dtype: bool